### ISSUE TITLE
handle properties that have non-c# valid names

### ISSUE THREAD

**Issue by Tyler-IN** [HavenDV/OpenApiGenerator#14]
Follow up issue after https://github.com/HavenDV/OpenApiGenerator/issues/12

Part of the spec I am working with has aspect ratios as property names as well, such as '1.5' and '16:9'.

Need to generalize the property name sanitization.

**Comment by HavenDV** [comment]
![image](https://github.com/HavenDV/OpenApiGenerator/assets/3002068/f5d8ca34-a59b-47de-8047-17628244c9a9)
https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names#naming-rules

**Comment by HavenDV** [comment]
Yes, I have so far taken the path of fixing single problems instead of a general universal solution.
This is what the search gave me

**Comment by HavenDV** [comment]
The problem is that some characters can be counted as separators between words, and some need to be replaced with something (as in your case). And it’s difficult to determine a universal rule without knowing unique cases

**Comment by Tyler-IN** [comment]
No arguments there.
Once you get down to defining property data, you have covered most other scenarios.

Here's my proposal,

```diff
@ src/libs/OpenApiGenerator.Core/Models/PropertyData.cs:52
-        if (name[0] is not ('_' or >= 'A' and <= 'Z' or >= 'a' and <= 'z'))
-        {
-            name = $"_{name}";
-        }
+         SanitizeName(ref name);
```

```cs
    private static void SanitizeName(ref string name)
    {
        bool InvalidFirstChar(char ch)
            => ch is not ('_' or >= 'A' and <= 'Z' or >= 'a' and <= 'z');

        bool InvalidSubsequentChar(char ch)
            => ch is not (
                    '_'
                    or >= 'A' and <= 'Z'
                    or >= 'a' and <= 'z'
                    or >= '0' and <= '9'
                );

        if (InvalidFirstChar(name[0]))
        {
            name = $"_{name}";
        }

        if (!name.Skip(1).Any(InvalidSubsequentChar)) return;

        Span<char> buf = stackalloc char[name.Length];
        for (var i = 1; i < buf.Length; i++)
        {
            if (InvalidSubsequentChar(buf[i]))
            {
                buf[i] = '_';
            }
        }

        // Span<char>.ToString implementation checks for char type, new string(&buf[0], buf.length)
        name = buf.ToString();
    }
```

**Comment by HavenDV** [comment]
I explored some valid properties:
![image](https://github.com/HavenDV/OpenApiGenerator/assets/3002068/fd5b0100-4b47-42b6-9eca-8866c1dab322)
But I’m not sure that this can be at least somehow useful and that it should be used.
Your solution is good, but I don't know how to combine it with division for words and automatic translation of each word into uppercase

**Comment by HavenDV** [comment]
Please also check my latest commit, I added separate tests for special cases and simple fix for your case, but I will think how to apply your latest PR

**Comment by Tyler-IN** [comment]
Hopefully this covers all of my use cases.

I think extending it to support these cases can be done with some effort.

I hope I got all of the changes rebased in.

Looking forward to using this project!

**Comment by HavenDV** [comment]
I released 0.8.5 with your latest changes, should be available soon

**Comment by Tyler-IN** [comment]
[dotnet/roslyn:src/Compilers/Core/Portable/InternalUtilities/UnicodeCharacterUtilities.cs](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/InternalUtilities/UnicodeCharacterUtilities.cs) outlines what makes valid property names.

Can maybe use that for reference when expanding SanitizeNames, etc.

**Comment by Tyler-IN** [comment]
This solves my use case, but noticed something else when adding the Twitch API...
Well... I'll create a new issue...

**Comment by Tyler-IN** [comment]
👍
