### ISSUE TITLE
comments from open api spec should be properly formatted into c# xml doc comments

### ISSUE THREAD

**Issue by Tyler-IN** [HavenDV/OpenApiGenerator#17]
When generating the Twitch test case, ran into some interesting documentation output...

![image](https://github.com/HavenDV/OpenApiGenerator/assets/33945568/ce709991-0b6a-46a6-a434-6c90a9f0ad42)

**Comment by HavenDV** [comment]
https://github.com/HavenDV/OpenApiGenerator/blob/1ac62a86a2a0951d78c704440058d2dc15ba0e87/src/libs/OpenApiGenerator.Core/Generation/Data.Methods.cs#L113

**Comment by HavenDV** [comment]
Ok, I added Twitch to Snapshots tests and fixed this issue, now it should compile without problems using 0.8.6
